# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "vmone" do |vmone|
    vmone.vm.box = "hashicorp/bionic64"
    vmone.vm.hostname = "ubuntu"
    vmone.vm.network "private_network", ip: "192.168.56.10"
    vmone.vm.provider "virtualbox" do |vb_vmone|
      vb_vmone.name = "ubuntu"
      vb_vmone.memory = "2048"
      vb_vmone.cpus = 2
    end
  end

  config.vm.provision "shell",
    inline: 'bash -c "$(curl https://raw.githubusercontent.com/abotias/scripts/master/install_docker_compose.sh)" -s "service"'

end
